/**
 * Tabletop card asset mapping: the concrete configuration for the asset
 * resolver seam. Stable art keys (derived from card types by the presentation
 * catalog) map to web-sized derivatives of the canonical repository art in
 * `/assets/cards`, generated by `apps/web/scripts/sync-card-assets.sh`.
 *
 * This file is the only place card image URLs live. Game logic, the engine,
 * and the protocol never see it; replacing the art means replacing this map
 * (or the files it points to) without touching rules.
 */
import type { CardAssetConfig } from '@/lib/game/asset-resolver';

/** Art key for the shared card back. It carries no card identity. */
export const CARD_BACK_ART_KEY = 'card/back';

/** Art keys for the per-player round/match result presets. */
export const RESULT_VICTORY_ART_KEY = 'result/victory';
export const RESULT_DEFEAT_ART_KEY = 'result/defeat';

/** Native ratio of the canonical card art (948x1659). */
export const CARD_ART_RATIO = '4 / 7';

export const TABLETOP_ASSET_CONFIG: CardAssetConfig = {
  images: {
    'card/robot-aspirador-real': '/cards/0.webp',
    'card/pecera-de-cristal': '/cards/1.webp',
    'card/raton-trampero': '/cards/2.webp',
    'card/conejito-guerrillero': '/cards/3.webp',
    'card/caparazon-armazon': '/cards/4.webp',
    'card/serpiente-encantadora': '/cards/5.webp',
    'card/saqueadog-de-tumbas': '/cards/6.webp',
    'card/malabarista-de-ocho-patas': '/cards/7.webp',
    'card/ermitano-busca-casa': '/cards/8.webp',
    'card/no-soy-una-mascota': '/cards/9.webp',
    'card/rey-gato': '/cards/10.webp',
    [CARD_BACK_ART_KEY]: '/cards/contraportada.webp',
    // Result presets: shown to each player according to their own outcome.
    [RESULT_VICTORY_ART_KEY]: '/cards/victoria.webp',
    [RESULT_DEFEAT_ART_KEY]: '/cards/derrota.webp',
  },
};
